version: '3.4'

services:
  api1:
    restart: on-failure
    build: ./web
    hostname: web1
    ports:
      - '81:5000'
  api2:
    restart: on-failure
    build: ./web
    hostname: api2
    ports:
      - '82:5000'
  nginx:
    build: ./nginx
    ports:
    - '80:80'
    depends_on:
    - api1
    - api2
